### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by chrissena** [SzymonPobiega/NServiceBus.EventStore#3]
This looks very interesting and I am considering using EventStore as a transport for NServiceBus but am not sure if this project is still actively maintained? 

Also, if I am storing my aggregate events in EventStore too I am unsure if this can be done transactionally in coordination with the transport of messages.

**Comment by Narvalex** [comment]
As far as I know, is not possible. EventStore can only make a transaction in one single stream. Why would you need to use NServiceBus for that? Is not easier to just susbcribe to the event store?

**Comment by SzymonPobiega** [comment]
@chrissena I am not working actively on it as there was not much interest in the community. But it is not dead and as soon as NSB 7 is released I will update this transport. As far as I can tell this is a "complete" thing (does not mean that there are no bugs, I just don't plan to add new features).

**Comment by SzymonPobiega** [comment]
@chrissena regarding the aggregates and messages:

1. As @Narvalex mentioned there is no cross-stream transactions so you can't get exactly-once processing similar to the case when you use e.g. SQL Server for both queues and data
2. You can have exactly-once processing semantics in Sagas via Outbox feature
3. You can also have exactly-once processing semantics in [Aggregates](https://github.com/SzymonPobiega/NServiceBus.EventStore/blob/master/src/NServiceBus.EventStore/EventSourcing/Aggregate.cs) via the Outbox feature

**Comment by chrissena** [comment]
Great. Thanks for the response.
